apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: cb-kubecd
    provider: github
    repository: jr-dev3
  name: cb-kubecd-jr-dev3
spec:
  description: Imported application for cb-kubecd/jr-dev3
  httpCloneURL: https://github.com/cb-kubecd/jr-dev3.git
  org: cb-kubecd
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jr-dev3
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/cb-kubecd/jr-dev3.git
